### ISSUE TITLE
Problemas para abrir os posts no painel do HumHub

### ISSUE THREAD

**Issue by alves1510** [humhub/sharebetween#66]
Bom dia,

Estou enfrentando um problema quando acesso meu HumHub. Sou administrador do site e quando acesso minha conta o painel não abre os posts. Segue mensagem que aparece pra mim quando acesso o erro.

{
    "url": "/index.php?r=dashboard%2Fdashboard%2Fstream",
    "status": 500,
    "response": "<pre>Exception 'yii\\base\\UnknownMethodException' with message 'Calling unknown method: humhub\\modules\\content\\models\\Content::getStateService()' \n\nin /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Component.php:300\n\nStack trace:\n#0 /home/faculda/fredbook.com.br/protected/modules/sharebetween/widgets/ShareLink.php(31): yii\\base\\Component-&gt;__call('getStateService', Array)\n#1 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Widget.php(146): humhub\\modules\\shareb...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception 'yii\\base\\UnknownMethodException' with message 'Calling unknown method: humhub\\modules\\content\\models\\Content::getStateService()' \n\nin /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Component.php:300\n\nStack trace:\n#0 /home/faculda/fredbook.com.br/protected/modules/sharebetween/widgets/ShareLink.php(31): yii\\base\\Component-&gt;__call('getStateService', Array)\n#1 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Widget.php(146): humhub\\modules\\sharebetween\\widgets\\ShareLink-&gt;run()\n#2 /home/faculda/fredbook.com.br/protected/humhub/widgets/BaseStack.php(88): yii\\base\\Widget::widget(Array)\n#3 /home/faculda/fredbook.com.br/protected/humhub/components/Widget.php(63): humhub\\widgets\\BaseStack-&gt;run()\n#4 /home/faculda/fredbook.com.br/protected/humhub/widgets/BaseStack.php(88): humhub\\components\\Widget::widget(Array)\n#5 /home/faculda/fredbook.com.br/protected/humhub/components/Widget.php(63): humhub\\widgets\\BaseStack-&gt;run()\n#6 /home/faculda/fredbook.com.br/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryFooter.php(16): humhub\\components\\Widget::widget(Array)\n#7 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/faculda/f...')\n#8 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile('/home/faculda/f...', Array)\n#9 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile('/home/faculda/f...', Array, Object(humhub\\modules\\post\\widgets\\WallEntry))\n#10 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\\base\\View-&gt;render('@content/widget...', Array, Object(humhub\\modules\\post\\widgets\\WallEntry))\n#11 /home/faculda/fredbook.com.br/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(294): yii\\base\\Widget-&gt;render('@content/widget...', Array)\n#12 /home/faculda/fredbook.com.br/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(227): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderFooter()\n#13 /home/faculda/fredbook.com.br/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderBody()\n#14 /home/faculda/fredbook.com.br/protected/humhub/components/Widget.php(63): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget-&gt;run()\n#15 [internal function]: humhub\\components\\Widget::widget(Array)\n#16 /home/faculda/fredbook.com.br/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func('humhub\\\\modules\\\\...', Array)\n#17 /home/faculda/fredbook.com.br/protected/humhub/modules/stream/actions/StreamEntryResponse.php(81): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget::renderStreamEntry(Object(humhub\\modules\\post\\models\\Post), Object(humhub\\modules\\content\\widgets\\stream\\WallStreamEntryOptions), Array)\n#18 /home/faculda/fredbook.com.br/protected/humhub/modules/stream/actions/Stream.php(414): humhub\\modules\\stream\\actions\\StreamEntryResponse::getAsArray(Object(humhub\\modules\\content\\models\\Content), Object(humhub\\modules\\content\\widgets\\stream\\WallStreamEntryOptions))\n#19 /home/faculda/fredbook.com.br/protected/humhub/modules/stream/actions/Stream.php(369): humhub\\modules\\stream\\actions\\Stream-&gt;getStreamEntryResult(Object(humhub\\modules\\content\\models\\Content), Object(humhub\\modules\\content\\widgets\\stream\\WallStreamEntryOptions))\n#20 /home/faculda/fredbook.com.br/protected/humhub/modules/stream/actions/Stream.php(348): humhub\\modules\\stream\\actions\\Stream-&gt;addResponseEntries(Array, Object(humhub\\modules\\stream\\actions\\StreamResponse))\n#21 [internal function]: humhub\\modules\\stream\\actions\\Stream-&gt;run()\n#22 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)\n#23 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\Action-&gt;runWithParams(Array)\n#24 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller-&gt;runAction('stream', Array)\n#25 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction('dashboard/dashb...', Array)\n#26 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#27 /home/faculda/fredbook.com.br/index.php(25): yii\\base\\Application-&gt;run()\n#28 {main}</pre>",
        "status": 500,
        "statusText": "error"
    },
    "dataType": "html",
    "html": "<pre>Exception 'yii\\base\\UnknownMethodException' with message 'Calling unknown method: humhub\\modules\\content\\models\\Content::getStateService()' \n\nin /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Component.php:300\n\nStack trace:\n#0 /home/faculda/fredbook.com.br/protected/modules/sharebetween/widgets/ShareLink.php(31): yii\\base\\Component-&gt;__call('getStateService', Array)\n#1 /home/faculda/fredbook.com.br/protected/vendor/yiisoft/yii2/base/Widget.php(146): humhub\\modules\\shareb...",
    "error": {},
    "errorThrown": "",
    "validationError": false
}
Um erro inesperado ocorreu no servidor. Se continuar acontecendo, favor informar um administrador.

Você tem ideia de como resolver?

Segue em anexo o print do problema. Desde já agradeço sua atenção.
![Uploading Painel(1).png…]()

**Comment by luke-** [comment]
Can you please reply in English.
We need steps to reproduce the problem. Ideally via our demo hosting.
